### ISSUE TITLE
link haye bala

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#1]
link aval samte rast, صفحه اصلی bashe.
ارتباط با ما yeki be akhar
درباره ما akhari bashe
link محصولات hazf beshe, chon safhe aval darimesh

![screen shot 2016-11-17 at 7 04 27 pm](https://cloud.githubusercontent.com/assets/15094271/20396997/5370331c-acfd-11e6-9603-50a917a2d1da.jpg)

@amirzakaria110

**Comment by amirzak11** [comment]
صفحه اصلی ثبت نام ارتباط با ما درباره ما   angam shod @jalal7h 
![form](https://cloud.githubusercontent.com/assets/20154765/20426743/c7f7f9de-ad95-11e6-87da-f49ff9a1aa47.png)
@jalal7h

**Comment by jalal7h** [comment]
OK.
@amirzakaria110
