### ISSUE TITLE
link haye footer

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#10]
link haye footer ro check kon age 404 hast, ye page barash doros kon, link az file template footer doros kon, k page dashte bashim tu admin, vali mohtava khali bashe moshkeli nist
age tunesti mohtava ham berizi k behtar
albate fekr mikonam axar e link ha page tu admin daran, fagaht baiad link esho doros koni.

@amirzakaria110

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
ax bede

@amirzakaria110

**Comment by amirzak11** [comment]
![4](https://cloud.githubusercontent.com/assets/20154765/20454020/2af16ef8-ae4a-11e6-99ac-6d3543c9afa9.png)
![3](https://cloud.githubusercontent.com/assets/20154765/20454021/2afa7a8e-ae4a-11e6-9fe2-afef4bd6897b.png)
![2](https://cloud.githubusercontent.com/assets/20154765/20454022/2afbe6b2-ae4a-11e6-9a45-1011ad696515.png)
![1](https://cloud.githubusercontent.com/assets/20154765/20454023/2afce468-ae4a-11e6-9ffb-f1db7e56d16f.png)
@jalal7h

**Comment by jalal7h** [comment]
OK.
@amirzakaria110
