### ISSUE TITLE
is_about

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#11]
alan admin bekhad matn e darbare-ma ro avaz kone, aval baiad bere php yad begire?
in che karie akhe
kollan component e is_about ro pak kon, matn ro tuye ye post-e-delkhah tuye modiriat-e-safahat besurate ye layer vared kon tu safhe darbare-ma

![screen shot 2016-11-18 at 7 41 00 pm](https://cloud.githubusercontent.com/assets/15094271/20436868/03cdc6d8-adc7-11e6-9329-7748fd1ceafc.jpg)

@amirzakaria110

**Comment by amirzak11** [comment]
خب من اینو گفتم ک گفتی نمیخواد همون طوری خوبی الان درستش میکنم 
@jalal7h

**Comment by jalal7h** [comment]
gofti barash ye form o save besazam, goftam na az layout ba post-delkhah bezan.
@amirzakaria110

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
ax bede

@amirzakaria110

**Comment by amirzak11** [comment]
![sd](https://cloud.githubusercontent.com/assets/20154765/20453966/bba2bffc-ae49-11e6-97fa-3cd59e6c348d.png)
@jalal7h

**Comment by jalal7h** [comment]
in ax che rabti be is_about dare?

@amirzakaria110

**Comment by amirzak11** [comment]
اشتباه فرستادم @jalal7h

**Comment by amirzak11** [comment]
![6](https://cloud.githubusercontent.com/assets/20154765/20454035/7d109254-ae4a-11e6-871b-eb1991f7d87e.png) @jalal7h

**Comment by jalal7h** [comment]
OK.
@amirzakaria110
