### ISSUE TITLE
#main_center width

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#12]
arz e main_center baiad sabet bashe
na 85%

alan arz e browser ro k yekam kam mikoni, sotun mahsul 2tai mishe.

![screen shot 2016-11-19 at 3 26 55 pm](https://cloud.githubusercontent.com/assets/15094271/20455244/b5ef127c-ae6c-11e6-9fcc-56f42f335e6b.jpg)

@amirzakaria110

**Comment by amirzakaria110** [comment]
anjam shod @jalal7h 
![100](https://cloud.githubusercontent.com/assets/20154765/20458273/842a6aae-aeb5-11e6-9624-3cf771a8b646.png)

**Comment by amirzak11** [comment]
anjam shod.
![screenshot from 2016-11-20 13 37 24](https://cloud.githubusercontent.com/assets/20154765/20462056/bd485ad2-af26-11e6-81eb-b3d4ee9079a0.png)
