### ISSUE TITLE
shomare slideshow + remove radius

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#13]
slideshow bedune dastkari ro barat gozashtam, 
bezar tuye proje, jaye uni k kharabesh kardi :-|

@amirzakaria110 
[slideshow-1.zip](https://github.com/jalal7h/norinmadar.com/files/601414/slideshow-1.zip)

**Comment by amirzak11** [comment]
انجام شد @jalal7h

**Comment by amirzak11** [comment]
![55](https://cloud.githubusercontent.com/assets/20154765/20458842/735e81d2-aec5-11e6-81ab-fd9e95291e0d.png)
@jalal7h
