### ISSUE TITLE
slideshow

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#3]
#slideshow be project ezafe kardam.
lotfan chan ta slide e monaseb peyda kon, ba tozihat e monaseb behesh ezafe kon
inai ke man gozashtamo pak kon, text e monaseb bezaria, yadet nare

@amirzakaria110

**Comment by amirzak11** [comment]
عکس آپلود نمیشه @jalal7h 
![ja](https://cloud.githubusercontent.com/assets/20154765/20426820/1a6dfc54-ad96-11e6-9f46-f96f89d34e7a.png)

**Comment by jalal7h** [comment]
matn e error e PHP ro bekhun, say kon motevajeh shi moshkel az kojas
az error haye php farar nakon, kheili kamel touzih mide 

@amirzakaria110

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
ax haye slide nabaid keshide beshe, chon ax ba zaribe size monaseb be slide nadadi keshide shode, in ke nokte hast k baiad beduni
va axat mof nemiarze
6 ta ax az LED gozashtam
baiad resize koni be 908x350
avalisho resize kardam
lotfan resize kon, bezar jaye in slide ha [ faghat ax ro avaz kon. ]

[led.zip](https://github.com/jalal7h/norinmadar.com/files/600319/led.zip)

**Comment by jalal7h** [comment]
ax haye slide nabaid keshide beshe, chon ax ba zaribe size monaseb be slide nadadi keshide shode, in ke nokte hast k baiad beduni

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
ax bede

@amirzakaria110

**Comment by amirzak11** [comment]
![10](https://cloud.githubusercontent.com/assets/20154765/20454088/607671d0-ae4b-11e6-8570-32f9dccbfccf.png)
@jalal7h

**Comment by jalal7h** [comment]
arz e ye ax 908 hast
baghie 900

engar man hamechio baiad check konam

@amirzakaria110

**Comment by amirzak11** [comment]
![slaid](https://cloud.githubusercontent.com/assets/20154765/20454837/616d0dbe-ae60-11e6-8d45-cc5a8d8a7a54.png) 
eslah shod @jalal7h

**Comment by jalal7h** [comment]
OK.
@amirzakaria110
