### ISSUE TITLE
text ro hazf kon az is_management_list

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#4]
text ro az list e mahsulat dar modirat bardar.
@amirzakaria110 

![screen shot 2016-11-17 at 7 36 23 pm](https://cloud.githubusercontent.com/assets/15094271/20396958/36f3af20-acfd-11e6-9a0a-8e156947579c.jpg)

**Comment by amirzak11** [comment]
![form](https://cloud.githubusercontent.com/assets/20154765/20426704/91845a00-ad95-11e6-8968-41a5f113931b.png)
anjam shod @jalal7h  @jalal7h

**Comment by jalal7h** [comment]
ax bede

@amirzakaria110

**Comment by jalal7h** [comment]
in k hamun jurie?!

@amirzakaria110

**Comment by amirzak11** [comment]
![gor](https://cloud.githubusercontent.com/assets/20154765/20427796/f29b3ae8-ad9a-11e6-8a98-9efa9697cf71.png)
  لیست بر اساس گروه بندی هم گذاشتم پاین سمت چپ @jalal7h

**Comment by jalal7h** [comment]
OK.
@amirzakaria110
