### ISSUE TITLE
form e sabt e mahsul

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#5]
yekam tamizesh kon
textarea { width: 100%; height: 150px }

@amirzakaria110 
![screen shot 2016-11-17 at 7 39 12 pm](https://cloud.githubusercontent.com/assets/15094271/20397071/9c44161c-acfd-11e6-93da-e0026c6f0627.jpg)

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
![formg](https://cloud.githubusercontent.com/assets/20154765/20426659/5f843b56-ad95-11e6-9f44-2985d6bf0421.png)
ax bede
anjam shod e khali shikam sir nemkone
@jalal7h 
@amirzakaria110

**Comment by jalal7h** [comment]
OK.
