### ISSUE TITLE
cat display

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#6]
alan ma namayeshi az cat nadarim

1. tu cat_config tanzim kon , k cat betune icon begire
2. baraye test, be har cat ye icon ghadd e ini k zamime in issue kardam ezafe kon
3. in icon ro tori bechin balaye list e mahsulat , ke 2ta cat kenar e ham ja beshe, yani har icon taghriban 50% safhe ro begire
4. layer e list e cat ha besurate ye layer e mostaghel az list mahsulat bashe )
5. esme cat ro ruye icon biar, hamuntor k tuye ax mibini, background esh siah bashe, in kar ro tuye html css baiad anjam bedi, 

6. in ax ha , link mishe be hamin safhe, monteha tahesh, &cat_id=123 va tuye query e marbut be list e mahsulat ham in cat_id ro begir, va tu query ezafe kon, k faghat un cat ro list kone.

![screen shot 2016-11-17 at 7 44 04 pm](https://cloud.githubusercontent.com/assets/15094271/20397249/535a790e-acfe-11e6-88f7-3c79041a2553.jpg)

![screen shot 2016-11-17 at 7 41 22 pm](https://cloud.githubusercontent.com/assets/15094271/20397255/584b807a-acfe-11e6-9f49-1e9b661aa897.jpg)

@amirzakaria110

**Comment by amirzak11** [comment]
![d](https://cloud.githubusercontent.com/assets/20154765/20426767/e3064460-ad95-11e6-8d94-4810e0cc4c44.png)
رو صفحه اصلی اومد ولی نتونستم لینکشو درست کنم  @jalal7h

**Comment by jalal7h** [comment]
1. fasele az bala bede
2. un kadr e tire, az pain az ax dar rafte
3. ax ha ro admin har size i bede, ma baiad ye size e moshakhas neshun bedim, lotfan fix kon rue ye size  e sabet, 

ina ro doros kon, ta be link beresim.

@amirzakaria110

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
moteghayeri ke baraye cat dar nazar gerefti "id" hast, taghir bede be "cat_id"
"id" ro mamulan baraye "item" ya hamun "mahsul" dar nazar migirim, 

@amirzakaria110

**Comment by jalal7h** [comment]
OK.
