### ISSUE TITLE
chinesh e mahsulat - safhe aval

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#7]
1. moteghayeri ke baraye cat dar nazar gerefti "id" hast, taghir bede be "cat_id"
2. safhe bandi baraye mahsulat nadarim alan, ezafe kon lotfan, ruye 9 ta fix kon.
3. align center hst, beshe rast, hamchenin arz e ".r" az 29 beshe 32% (ax zamime)

![screen shot 2016-11-18 at 7 02 57 pm](https://cloud.githubusercontent.com/assets/15094271/20435555/cfa4947c-adc1-11e6-9a45-b7bb3774427f.jpg)
![screen shot 2016-11-18 at 7 03 07 pm](https://cloud.githubusercontent.com/assets/15094271/20435556/cfab68b0-adc1-11e6-881a-f99b902943a1.jpg)
![screen shot 2016-11-18 at 7 03 16 pm](https://cloud.githubusercontent.com/assets/15094271/20435554/cfa347e8-adc1-11e6-9c29-2a3eb6f249c6.jpg)

**Comment by amirzak11** [comment]
anjam shod push kardam @jalal7h

**Comment by jalal7h** [comment]
moteghayeri ke baraye cat dar nazar gerefti "id" hast, taghir bede be "cat_id"
"id" ro mamulan baraye "item" ya hamun "mahsul" dar nazar migirim,
- align hanuz center e

![screen shot 2016-11-18 at 7 20 04 pm](https://cloud.githubusercontent.com/assets/15094271/20436147/3cc713fc-adc4-11e6-8dad-001e29018747.jpg)

**Comment by amirzak11** [comment]
moteghayeri ke baraye cat dar nazar gerefti "id" hast, taghir bede be "cat_id"
"id" ro mamulan baraye "item" ya hamun "mahsul" dar nazar migirim, متوجه نشدم کجا رو میگی @jalal7h

**Comment by jalal7h** [comment]
&id=

-->

&cat_id=

motevajeh shodi?

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
ax bede

@amirzakaria110

**Comment by amirzak11** [comment]
![8](https://cloud.githubusercontent.com/assets/20154765/20454078/3c89edba-ae4b-11e6-8c00-f07f0a4c8294.png) @jalal7h

**Comment by jalal7h** [comment]
bebin, 
man in ax ro chand bar baiad bezaram? 
alan dafe 3 ya 4 hast ke daram migam in center e , bendazesh right.
aslan nemikhuni

![3cc713fc-adc4-11e6-8dad-001e29018747](https://cloud.githubusercontent.com/assets/15094271/20454091/66dcd1ea-ae4b-11e6-95f2-cf0975febf7a.jpg)

@amirzakaria110

**Comment by amirzak11** [comment]
![12](https://cloud.githubusercontent.com/assets/20154765/20454121/148c66de-ae4c-11e6-8b7e-f71944d482ff.png)
dorostesh kardam @jalal7h

**Comment by jalal7h** [comment]
OK.

@amirzakaria110
