### ISSUE TITLE
META [ keywords, description ]

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#8]
in mored az admin > tarh e safhe anjam mishe. unja ye function midi, tu function kar mikoni

1. category :: title == esme daste
2. category :: keywords == esme daste, ke space ha ba virgul jaygozin shode.
3. category :: description == esme daste

4. item :: title == esme item
5. item :: keywords == esme daste + esme item, ke space ha ba virgul jaygozin shode.
6. item :: description == tozihat, ke \n replace shode ba space

@amirzakaria110 

![screen shot 2016-11-18 at 7 24 23 pm](https://cloud.githubusercontent.com/assets/15094271/20436289/ea294060-adc4-11e6-8779-0b988d6b757e.jpg)

- - - - - - - - - - - -

![screen shot 2016-11-18 at 7 27 43 pm](https://cloud.githubusercontent.com/assets/15094271/20436333/1bb79244-adc5-11e6-9ca1-4c64de04b057.jpg)

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by amirzak11** [comment]
![7](https://cloud.githubusercontent.com/assets/20154765/20454062/f705ba80-ae4a-11e6-8a27-e29f96c9bc3c.png) @jalal7h

**Comment by jalal7h** [comment]
na, faghat pichundi
aslan nakhundi man chi neveshtam,

@amirzakaria110

**Comment by amirzak11** [comment]
![sd](https://cloud.githubusercontent.com/assets/20154765/20458808/7072540e-aec4-11e6-973c-8714d6f92bf8.png)
item :: description == tozihat, ke \n replace shode ba space
این درسته ؟
@jalal7h

**Comment by amirzak11** [comment]
![desc](https://cloud.githubusercontent.com/assets/20154765/20458857/c65f2b20-aec5-11e6-900f-22f67d0f0a67.png)
@jalal7h
