### ISSUE TITLE
آر اس اس محصولات

### ISSUE THREAD

**Issue by jalal7h** [jalal7h/norinmadar.com#9]
tuye footer rss mahsulat
link shode be autopart.
kamel checkesh kon, va dorosesh kon

@amirzakaria110

**Comment by amirzak11** [comment]
anjam shod @jalal7h

**Comment by jalal7h** [comment]
ax bede

@amirzakaria110

**Comment by amirzak11** [comment]
![3](https://cloud.githubusercontent.com/assets/20154765/20454040/96aef3e0-ae4a-11e6-8bcd-cffceee1d5be.png)
@jalal7h

**Comment by jalal7h** [comment]
ax rabti be mozu nadare
mikhai proje ro cancel koni? kolan halo hosele kar ro nadari engar

@amirzakaria110

**Comment by amirzak11** [comment]
![11](https://cloud.githubusercontent.com/assets/20154765/20454101/9dbe34a6-ae4b-11e6-9ef1-aa2a7c32f673.png)
@jalal7h

**Comment by amirzak11** [comment]
نه چند تا عکس شبیه همه اشتباه فرستادم @jalal7h

**Comment by jalal7h** [comment]
kalame AUTOPART ro doros kon, avaz kon be product
vaghean nemiduni k baiad in kar anjam beshe? napichun

@amirzakaria110

**Comment by amirzak11** [comment]
![1](https://cloud.githubusercontent.com/assets/20154765/20458812/b36b1ab6-aec4-11e6-89a2-cd7db0099798.png)
autopars ro kardam product vali file xml ro peyda nakardam dorostesh konam autopars bod kar mekard alan kar nmekone @jalal7h
